# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/runtime-7.17.2" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.17.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.17.2.tgz";
        sha512 = "hzeyJyMA1YGdJTuWU0e/j4wKXrU4OMFvY2MSlaI9B7VQb0r5cxTE3EAIS2Q7Tn2RIcDkRvTA/v2JsAEhxe99uw==";
      };
    };
    "@babel/runtime-corejs2-7.17.2" = {
      name = "_at_babel_slash_runtime-corejs2";
      packageName = "@babel/runtime-corejs2";
      version = "7.17.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime-corejs2/-/runtime-corejs2-7.17.2.tgz";
        sha512 = "EamjJvKlHTdSmJ8t6yHtqttdiA3xThvTNdmGb0Kh0oqRhV1SU2JGFU5TjVCg35Vnn8MYfUBHHtLZYHIY+W28qw==";
      };
    };
    "@types/node-10.17.60" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "10.17.60";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-10.17.60.tgz";
        sha512 = "F0KIgDJfy2nA3zMLmWGKxcH2ZVEtCZXHHdOQs2gSaQ27+lNeEfGxzkIw90aXswATX7AZ33tahPbzy6KAfUreVw==";
      };
    };
    "@types/node-13.13.52" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "13.13.52";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-13.13.52.tgz";
        sha512 = "s3nugnZumCC//n4moGGe6tkNMyYEdaDBitVjwPxXmR5lnMG5dHePinH2EdxkG3Rh1ghFHHixAG4NJhpJW1rthQ==";
      };
    };
    "@types/node-14.18.12" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "14.18.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-14.18.12.tgz";
        sha512 = "q4jlIR71hUpWTnGhXWcakgkZeHa3CCjcQcnuzU8M891BAWA2jHiziiWEPEkdS5pFsz7H9HJiy8BrK7tBRNrY7A==";
      };
    };
    "@types/yargs-15.0.14" = {
      name = "_at_types_slash_yargs";
      packageName = "@types/yargs";
      version = "15.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/yargs/-/yargs-15.0.14.tgz";
        sha512 = "yEJzHoxf6SyQGhBhIYGXQDSCkJjB6HohDShto7m8vaKg9Yp0Yn8+71J9eakh2bnPg6BfsH9PRMhiRTZnd4eXGQ==";
      };
    };
    "@types/yargs-parser-21.0.0" = {
      name = "_at_types_slash_yargs-parser";
      packageName = "@types/yargs-parser";
      version = "21.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/yargs-parser/-/yargs-parser-21.0.0.tgz";
        sha512 = "iO9ZQHkZxHn4mSakYV0vFHAVDyEOIJQrV2uZ06HxEPcx+mt8swXoZHIbaaJ2crJYFfErySgktuTZ3BeLz+XmFA==";
      };
    };
    "JSONStream-1.3.5" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-1.3.5.tgz";
        sha512 = "E+iruNOY8VV9s4JEbe1aNEm6MiszPRr/UfcHMz0TQh1BXSxHK+ASV1R6W4HpjBhSeS+54PIsAMCBmwD06LLsqQ==";
      };
    };
    "advanced-map-base-0.0.4" = {
      name = "advanced-map-base";
      packageName = "advanced-map-base";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/advanced-map-base/-/advanced-map-base-0.0.4.tgz";
        sha512 = "auTlMKEPMll9I6InsV7XNbDRfTra8u9kBd73/rSe0VuzYFFyAU5mb41wpV8Urs/1CYb+ysE+FetN6zRxfhC0EQ==";
      };
    };
    "advanced-map-initialized-0.0.4" = {
      name = "advanced-map-initialized";
      packageName = "advanced-map-initialized";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/advanced-map-initialized/-/advanced-map-initialized-0.0.4.tgz";
        sha512 = "mvPQ6Q1ZwUZ3Uwseh/8jog/PC2E6OmmpUYir5+eGkBw0eoMYAF880qYL1NTIS9k5jW1NExyV2ADoqVLzZ4pePA==";
      };
    };
    "advanced-map-types-0.0.4" = {
      name = "advanced-map-types";
      packageName = "advanced-map-types";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/advanced-map-types/-/advanced-map-types-0.0.4.tgz";
        sha512 = "1z2ags9Y3SbsvRBsANA60J8HGfWeEOnrFwavN72EIQVCt/iFB6fujjvf8dwER7Xpo7tttPfxWxnLnvCiFHU7hA==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "camelcase-5.3.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "5.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-5.3.1.tgz";
        sha512 = "L28STB170nwWS63UjtlEOE3dldQApaJXZkOI1uMFfzf3rRuPegHaHesyee+YxQ+W6SvRDQV6UrdOdRiR153wJg==";
      };
    };
    "cliui-6.0.0" = {
      name = "cliui";
      packageName = "cliui";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-6.0.0.tgz";
        sha512 = "t6wbgtoCXvAzst7QgXxJYqPt0usEfbgQdftEPbLL/cvv6HPE5VgvqCuAIDR0NgU52ds6rFwqrgakNLrHEjCbrQ==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "core-js-2.6.12" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.6.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.6.12.tgz";
        sha512 = "Kb2wC0fvsWfQrgk8HU5lW6U/Lcs8+9aaYcy4ZFc6DDlo4nZ7n70dEgE5rtR0oG6ufKDUnrwfWL1mXR5ljDatrQ==";
      };
    };
    "core-util-is-1.0.3" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.3.tgz";
        sha512 = "ZQBvi1DcpJ4GDqanjucZ2Hj3wEO5pZDS89BWbkcrvdxksJorwUDDZamX9ldFkp9aw2lmBDLgkObEA4DWNJ9FYQ==";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "f6534d15148269b20352e7bee26f501f9a191290";
      };
    };
    "dequeue-1.0.5" = {
      name = "dequeue";
      packageName = "dequeue";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/dequeue/-/dequeue-1.0.5.tgz";
        sha1 = "10f1cef07e3234b21dcb38f4bfa2d66034ab67c7";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "find-up-4.1.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-4.1.0.tgz";
        sha512 = "PpOwAdQ/YlXQ2vj8a3h8IipDuYRi3wceVQQGYWxNINccq40Anw7BlsEXCMbt1Zt+OLA6Fq9suIpIWD0OsnISlw==";
      };
    };
    "get-caller-file-2.0.5" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz";
        sha512 = "DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "iter-tools-6.2.6" = {
      name = "iter-tools";
      packageName = "iter-tools";
      version = "6.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/iter-tools/-/iter-tools-6.2.6.tgz";
        sha512 = "DlBSv7cIrM214wYFxyz4vg98BmEpxFTGx37ei/ktYT05shJHoDwz7wuaPx3XhaJi1uGEc5bM+vUBWhm3z6yNIg==";
      };
    };
    "jsonparse-1.3.1" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-1.3.1.tgz";
        sha1 = "3f4dae4a91fac315f71062f8521cc239f1366280";
      };
    };
    "little-ds-toolkit-1.1.1" = {
      name = "little-ds-toolkit";
      packageName = "little-ds-toolkit";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/little-ds-toolkit/-/little-ds-toolkit-1.1.1.tgz";
        sha512 = "Zl5flhnd5W6nhRCyoL1bNlU8M5CWFp6SItMmK4pj39LKgzQD7LGg591OJ0jwDKat7mjHvJVkOyJT+BXOQH4iXw==";
      };
    };
    "locate-path-5.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-5.0.0.tgz";
        sha512 = "t7hw9pI+WvuwNJXwk5zVHpyhIqzg2qTlklJOf0mVxGSbe3Fp2VieZcduNYjaLDoy6p9uGpQEGWG87WpMKlNq8g==";
      };
    };
    "markdown-table-0.4.0" = {
      name = "markdown-table";
      packageName = "markdown-table";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-table/-/markdown-table-0.4.0.tgz";
        sha1 = "890c2c1b3bfe83fb00e4129b8e4cfe645270f9d1";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "p-limit-2.3.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-2.3.0.tgz";
        sha512 = "//88mFWSJx8lxCzwdAABTJL2MyWB12+eIY7MDL2SqLmAkeKU9qxRvWuSyTjm3FUmpBEMuFfckAIqEaVGUDxb6w==";
      };
    };
    "p-locate-4.1.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-4.1.0.tgz";
        sha512 = "R79ZZ/0wAxKGu3oYMlz8jy/kbhsNrS7SKZ7PxEHBgJ5+F2mtFW2fK2cOtBh1cHYkQsbzFV7I+EoRKe6Yt0oK7A==";
      };
    };
    "p-try-2.2.0" = {
      name = "p-try";
      packageName = "p-try";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-try/-/p-try-2.2.0.tgz";
        sha512 = "R4nPAVTAU0B9D35/Gk3uJf/7XYbQcyohSKdvAxIRSNghFl4e71hVoGnBNQz9cWaXxO2I10KTC+3jMdvvoKw6dQ==";
      };
    };
    "parse-markdown-table-0.0.6" = {
      name = "parse-markdown-table";
      packageName = "parse-markdown-table";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-markdown-table/-/parse-markdown-table-0.0.6.tgz";
        sha512 = "x0j5JB8qrLa4tBsW9RU4F3ZPPBXMs6fccH7jgLXQhAZrptvv5DaJXtmpKKkZvZYyRAXF6HI83fGUp3RND65Wkg==";
      };
    };
    "path-exists-4.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-4.0.0.tgz";
        sha512 = "ak9Qy5Q7jYb2Wwcey5Fpvg2KoAc/ZIhLSLOSBmRmygPsGwkVVt0fZa0qrtMz+m6tJTAHfZQ8FnmB4MG4LWy7/w==";
      };
    };
    "readable-stream-1.0.34" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.0.34";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.34.tgz";
        sha1 = "125820e34bc842d2f2aaafafe4c2916ee32c157c";
      };
    };
    "regenerator-runtime-0.13.9" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.9.tgz";
        sha512 = "p3VT+cOEgxFsRRA9X4lkI1E+k2/CtnKtU4gcxyaCUreilL/vqI6CdZ3wxVUx3UOUg+gnUOQQcRI7BmSI656MYA==";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha1 = "8c64ad5fd30dab1c976e2344ffe7f792a6a6df42";
      };
    };
    "require-main-filename-2.0.0" = {
      name = "require-main-filename";
      packageName = "require-main-filename";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-main-filename/-/require-main-filename-2.0.0.tgz";
        sha512 = "NKN5kMDylKuldxYLSUfrbo5Tuzh4hd+2E8NPPX02mZtn1VuREQToYe/ZdlJy+J3uCpfaiGF05e7B8W0iXbQHmg==";
      };
    };
    "set-blocking-2.0.0" = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "045f9782d011ae9a6803ddd382b24392b3d890f7";
      };
    };
    "simple-fake-console-0.1.8" = {
      name = "simple-fake-console";
      packageName = "simple-fake-console";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-fake-console/-/simple-fake-console-0.1.8.tgz";
        sha512 = "y5wDxCYodQOWTQBJI2p57oIvaTU+rvGVNmm/s/O8lCWiPhUHWzXcWO2q38/Qg5AV7isgfpOb9/u+o8StIKkBEQ==";
      };
    };
    "string-stream-utils-0.0.4" = {
      name = "string-stream-utils";
      packageName = "string-stream-utils";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-stream-utils/-/string-stream-utils-0.0.4.tgz";
        sha512 = "G3lY8tnUvOlefwxMZRjk6grELUfyvUwejx4v0AMY6medG+flO+XmpKlRJwgSDsYugezgVCzX/8mqpLl5fC7MpQ==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "table-parser-base-0.0.5" = {
      name = "table-parser-base";
      packageName = "table-parser-base";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/table-parser-base/-/table-parser-base-0.0.5.tgz";
        sha512 = "f3+/0kdrIVLY1E+TO2cTCuWiOWKTm4GMtCHyVsQutpSHobYYedQu+PTVwT08FOmOglWMvP0NFN+WISdYDAb2Lg==";
      };
    };
    "terminus-1.0.12" = {
      name = "terminus";
      packageName = "terminus";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/terminus/-/terminus-1.0.12.tgz";
        sha1 = "0a93ad36d95c06259100db60615252862ac17773";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "through2-0.5.1" = {
      name = "through2";
      packageName = "through2";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-0.5.1.tgz";
        sha1 = "dfdd012eb9c700e2323fd334f38ac622ab372da7";
      };
    };
    "through2-map-1.4.0" = {
      name = "through2-map";
      packageName = "through2-map";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2-map/-/through2-map-1.4.0.tgz";
        sha1 = "7cb13e7c9ef00c7a93c742567f9d2e51168ff7f5";
      };
    };
    "tslib-1.14.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.14.1.tgz";
        sha512 = "Xni35NKzjgMrwevysHTCArtLDpPvye8zV/0E4EyYn43P7/7qvQwPh9BGkHewbMulVntbigmcT7rdX3BNo9wRJg==";
      };
    };
    "tslib-2.3.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.3.1.tgz";
        sha512 = "77EbyPPpMz+FRFRuAFlWMtmgUWGe9UOG2Z25NqCwiIjRhOf5iKGuzSe5P2w1laq+FkRy4p+PCuVkJSGkzTEKVw==";
      };
    };
    "typescript-compare-0.0.2" = {
      name = "typescript-compare";
      packageName = "typescript-compare";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript-compare/-/typescript-compare-0.0.2.tgz";
        sha512 = "8ja4j7pMHkfLJQO2/8tut7ub+J3Lw2S3061eJLFQcvs3tsmJKp8KG5NtpLn7KcY2w08edF74BSVN7qJS0U6oHA==";
      };
    };
    "typescript-logic-0.0.0" = {
      name = "typescript-logic";
      packageName = "typescript-logic";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript-logic/-/typescript-logic-0.0.0.tgz";
        sha512 = "zXFars5LUkI3zP492ls0VskH3TtdeHCqu0i7/duGt60i5IGPIpAHE/DWo5FqJ6EjQ15YKXrt+AETjv60Dat34Q==";
      };
    };
    "typescript-miscellaneous-0.1.1" = {
      name = "typescript-miscellaneous";
      packageName = "typescript-miscellaneous";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript-miscellaneous/-/typescript-miscellaneous-0.1.1.tgz";
        sha512 = "dyGMilZPOL/qQMlJSWK+SbQyJpf6YZZPmPrbbdHGkAvGUvlhv4kGKTgddXWLxFWHTirR2I0VfD8mSwia3WLGtA==";
      };
    };
    "typescript-tuple-2.2.1" = {
      name = "typescript-tuple";
      packageName = "typescript-tuple";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript-tuple/-/typescript-tuple-2.2.1.tgz";
        sha512 = "Zcr0lbt8z5ZdEzERHAMAniTiIKerFCMgd7yjq1fPnDJ43et/k9twIFQMUYff9k5oXcsQ0WpvFcgzK2ZKASoW6Q==";
      };
    };
    "typescript-union-0.1.2" = {
      name = "typescript-union";
      packageName = "typescript-union";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript-union/-/typescript-union-0.1.2.tgz";
        sha512 = "pzfdtUZ8teglF69/dllzgd6yV7ikoszPHVyOkl4WGICRhTJgCTwL3+ZnnF/hvII536VbsNMQfd9GmLBNhtsmgg==";
      };
    };
    "utility-types-3.10.0" = {
      name = "utility-types";
      packageName = "utility-types";
      version = "3.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utility-types/-/utility-types-3.10.0.tgz";
        sha512 = "O11mqxmi7wMKCo6HKFt5AhO4BwY3VV68YU07tgxfz8zJTIxr4BpsezN49Ffwy9j3ZpwwJp4fkRwjRzq3uWE6Rg==";
      };
    };
    "which-module-2.0.0" = {
      name = "which-module";
      packageName = "which-module";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-module/-/which-module-2.0.0.tgz";
        sha1 = "d9ef07dce77b9902b8a3a8fa4b31c3e3f7e6e87a";
      };
    };
    "wrap-ansi-6.2.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-6.2.0.tgz";
        sha512 = "r6lPcBGxZXlIcymEu7InxDMhdW0KDxpLgoFLcguasxCaJ/SOIZwINatK9KY/tf+ZrlywOKU0UDj3ATXUBfxJXA==";
      };
    };
    "xtend-3.0.0" = {
      name = "xtend";
      packageName = "xtend";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-3.0.0.tgz";
        sha1 = "5cce7407baf642cba7becda568111c493f59665a";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
    "y18n-4.0.3" = {
      name = "y18n";
      packageName = "y18n";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-4.0.3.tgz";
        sha512 = "JKhqTOwSrqNA1NY5lSztJ1GrBiUodLMmIZuLiDaMRJ+itFd+ABVE8XBjOvIWL+rSqNDC74LCSFmlb/U4UZ4hJQ==";
      };
    };
    "yargs-15.4.1" = {
      name = "yargs";
      packageName = "yargs";
      version = "15.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-15.4.1.tgz";
        sha512 = "aePbxDmcYW++PaqBsJ+HYUFwCdv4LVvdnhBy78E57PIor8/OVvhMrADFFEDh8DHDFRv/O9i3lPhsENjO7QX0+A==";
      };
    };
    "yargs-parser-18.1.3" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "18.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-18.1.3.tgz";
        sha512 = "o50j0JeToy/4K6OZcaQmW6lyXXKhq7csREXcDwk2omFPJEwUNOVtJKvmDr9EI1fAJZUyZcRF7kxGBWmRXudrCQ==";
      };
    };
  };
in
{
  markdown-table-cli = nodeEnv.buildNodePackage {
    name = "markdown-table-cli";
    packageName = "markdown-table-cli";
    version = "1.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/markdown-table-cli/-/markdown-table-cli-1.0.1.tgz";
      sha1 = "83b764453462a7951fd29adc44a765897b623257";
    };
    dependencies = [
      sources."JSONStream-1.3.5"
      sources."core-util-is-1.0.3"
      sources."inherits-2.0.4"
      sources."isarray-0.0.1"
      sources."jsonparse-1.3.1"
      sources."markdown-table-0.4.0"
      sources."minimist-1.2.5"
      sources."readable-stream-1.0.34"
      sources."string_decoder-0.10.31"
      (sources."terminus-1.0.12" // {
        dependencies = [
          sources."xtend-4.0.2"
        ];
      })
      sources."through-2.3.8"
      sources."through2-0.5.1"
      sources."through2-map-1.4.0"
      sources."xtend-3.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Format JSON as Markdown table on the command-line";
      homepage = "https://github.com/raine/markdown-table-cli#readme";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  parse-markdown-table-cli = nodeEnv.buildNodePackage {
    name = "parse-markdown-table-cli";
    packageName = "parse-markdown-table-cli";
    version = "0.0.6";
    src = fetchurl {
      url = "https://registry.npmjs.org/parse-markdown-table-cli/-/parse-markdown-table-cli-0.0.6.tgz";
      sha512 = "it/WFVY9DSdAdlKQju4bwmJgUgEjwsJNLethb4xEJaUB61zK3Wyi6LP7tEliWLlxLPbUDQIk12W8Dp63SRG+hA==";
    };
    dependencies = [
      sources."@babel/runtime-7.17.2"
      sources."@babel/runtime-corejs2-7.17.2"
      sources."@types/node-14.18.12"
      sources."@types/yargs-15.0.14"
      sources."@types/yargs-parser-21.0.0"
      (sources."advanced-map-base-0.0.4" // {
        dependencies = [
          sources."@types/node-13.13.52"
          sources."tslib-1.14.1"
        ];
      })
      (sources."advanced-map-initialized-0.0.4" // {
        dependencies = [
          sources."@types/node-13.13.52"
          sources."tslib-1.14.1"
        ];
      })
      (sources."advanced-map-types-0.0.4" // {
        dependencies = [
          sources."@types/node-13.13.52"
          sources."tslib-1.14.1"
        ];
      })
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-4.3.0"
      sources."camelcase-5.3.1"
      sources."cliui-6.0.0"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."core-js-2.6.12"
      sources."decamelize-1.2.0"
      sources."dequeue-1.0.5"
      sources."emoji-regex-8.0.0"
      sources."find-up-4.1.0"
      sources."get-caller-file-2.0.5"
      sources."is-fullwidth-code-point-3.0.0"
      sources."iter-tools-6.2.6"
      sources."little-ds-toolkit-1.1.1"
      sources."locate-path-5.0.0"
      sources."p-limit-2.3.0"
      sources."p-locate-4.1.0"
      sources."p-try-2.2.0"
      sources."parse-markdown-table-0.0.6"
      sources."path-exists-4.0.0"
      sources."regenerator-runtime-0.13.9"
      sources."require-directory-2.1.1"
      sources."require-main-filename-2.0.0"
      sources."set-blocking-2.0.0"
      sources."simple-fake-console-0.1.8"
      sources."string-stream-utils-0.0.4"
      sources."string-width-4.2.3"
      sources."strip-ansi-6.0.1"
      sources."table-parser-base-0.0.5"
      sources."tslib-2.3.1"
      sources."typescript-compare-0.0.2"
      sources."typescript-logic-0.0.0"
      (sources."typescript-miscellaneous-0.1.1" // {
        dependencies = [
          sources."@types/node-10.17.60"
          sources."tslib-1.14.1"
        ];
      })
      sources."typescript-tuple-2.2.1"
      sources."typescript-union-0.1.2"
      sources."utility-types-3.10.0"
      sources."which-module-2.0.0"
      sources."wrap-ansi-6.2.0"
      sources."y18n-4.0.3"
      sources."yargs-15.4.1"
      sources."yargs-parser-18.1.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Convert a markdown table from text to JSON objects";
      homepage = "https://ksxnodeapps.github.io/fun-little-utilities/";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
